### ISSUE TITLE
Resque worker throws undefined local_constants method for Segment::Analytics

### ISSUE THREAD

**Issue by idl3** [segmentio/analytics-ruby#107]
Trying to run a resque worker and it throws the following error, any idea what may cause this? Is it a resque problem?

```
bundle exec rake environment resque:work QUEUE=mailer                                                                                                                                                                               rvm:ruby-2.2.3
rake aborted!
NoMethodError: undefined method `local_constants' for #<Segment::Analytics:0x007fe311510b48>
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/analytics-ruby-2.1.0/lib/segment/analytics.rb:21:in `method_missing'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:146:in `block in watch_namespaces'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:143:in `map'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:143:in `watch_namespaces'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:643:in `new_constants_in'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:456:in `load_file'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:354:in `require_or_load'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:317:in `depend_on'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:233:in `require_dependency'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5.1/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5.1/lib/rails/engine.rb:471:in `each'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5.1/lib/rails/engine.rb:471:in `block in eager_load!'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5.1/lib/rails/engine.rb:469:in `each'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5.1/lib/rails/engine.rb:469:in `eager_load!'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/resque-1.26.0/lib/resque/tasks.rb:43:in `block (2 levels) in <top (required)>'
/Users/ernie/.rvm/gems/ruby-2.2.3/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/ernie/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/ernie/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => resque:work => resque:preload
(See full trace by running task with --trace)
```

**Comment by nickfishman** [comment]
I ran into something similar. It happened because I had a subdirectory within my app folder named the same as the class I was trying to use elsewhere. This seems to be an issue with the Rails autoloader.

**Comment by ravensnowbird** [comment]
We had a similar issue because of an issue with the naming convention

`
require 'segment'
Analytics = if Rails.env.test?
  FakeAnalyticsRuby.new
else
  Segment::Analytics.new(
    write_key: Rails.application.secrets.write_key,
    on_error: proc { |_status, msg| print msg },
    max_queue_size: 25_000
  )
end
`

As we wanted to use a Module style of method access we fixed it by doing this

`
require 'segment'
$analytics = if Rails.env.test?
  FakeAnalyticsRuby.new
else
  Segment::Analytics.new(
    write_key: Rails.application.secrets.write_key,
    on_error: proc { |_status, msg| print msg },
    max_queue_size: 25_000
  )
end

module Analytics
  def self.method_missing message, *args, &block
    $analytics.send message, *args, &block
  end

  def self.respond_to? method_name
    $analytics.respond_to?(method_name)
  end
end
`
