### ISSUE TITLE
wrong argument type nil (expected String) 

### ISSUE THREAD

**Issue by belongstorachel** [segmentio/analytics-ruby#266]
We recently upgraded our Ruby version of our application to 3.1.2. We are currently using Rails 6.0.

It seems that since our Ruby upgrade, the ruby-analytics gem throws "[analytics-ruby] wrong argument type nil (expected String)" We recently increased the amount of track & identify calls we are making to Segment and the instances of these errors are growing.

We are calling `if Analytics.queued_messages >= 9_000`

This is the stack trace that we have. (Note that the last line is what we have in the `on_error: Proc.new { |status, msg| puts "Segment Error: #{status}, #{msg}" })`

```
14:48:30.844
[analytics-ruby] wrong argument type nil (expected String)

14:48:30.844
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/object/json.rb:39:in `to_json'

14:48:30.845
[analytics-ruby] /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `to_json'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:110:in `generate'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:110:in `send_request'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:42:in `block in send'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:92:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:92:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:102:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:102:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:102:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:102:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:102:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:102:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:102:in `retry_with_backoff'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/transport.rb:41:in `send'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/worker.rb:45:in `run'

14:48:30.845
[analytics-ruby] /app/vendor/bundle/ruby/3.1.0/gems/analytics-ruby-2.4.0/lib/segment/analytics/client.rb:191:in `block (2 levels) in ensure_worker_running'

14:48:30.845
Segment Error: -1, wrong argument type nil (expected String)
```

**Comment by belongstorachel** [comment]
We found the source of this issue. It has to do with a newer version of the `oj` gem. We were previously at 3.10.14, and upgraded to 3.14.3 which caused this error. When we reverted it back to 3.10.14, it stopped generating this error.
